FROM ubuntu:latest

RUN apt update && apt upgrade -y && apt install -y mysql-server nano

RUN ["/bin/bash", "-c", "debconf-set-selections <<< 'mysql-server mysql-server/root_password password zfEFDJr562Mv59sP5q'"]
RUN ["/bin/bash", "-c", "debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password zfEFDJr562Mv59sP5q'"]

RUN mkdir /var/run/mysqld \
 && chown -R mysql:mysql /var/run/mysqld

COPY test.sql /doc
COPY userAuthentif /doc

RUN chmod u+x /doc/userAuthentif
RUN /doc/userAuthentif

COPY mysqld.cnf /etc/mysql/mysql.conf.d/

EXPOSE 3306

CMD mysqld_safe
